<?php

use Illuminate\Database\Seeder;
use Database\DisableForeignKeys;
use Database\TruncateTable;
use Carbon\Carbon;

class MedicineGenericNameTableSeeder extends Seeder
{
    use DisableForeignKeys, TruncateTable;

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->disableForeignKeys();

        $this->truncate(config('access.medicine_generic_name_table'));

        $medicineGenericNames = [
            [
                'name'          => 'Alendronate Tablet',
                'code'          => 'MGN0001',
                'description'   => 'Alendronate Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Acyclovir Capsule',
                'code'          => 'MGN0002',
                'description'   => 'Acyclovir Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Acyclovir Tablet',
                'code'          => 'MGN0003',
                'description'   => 'Acyclovir Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Albuterol Inhalation Solution ',
                'code'          => 'MGN0004',
                'description'   => 'Albuterol Inhalation Solution ',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Albuterol Sulfate',
                'code'          => 'MGN0005',
                'description'   => 'Albuterol Sulfate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Alclometasone Dipropionate Cream',
                'code'          => 'MGN0006',
                'description'   => 'Alclometasone Dipropionate Cream',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Alfuzosin HCL',
                'code'          => 'MGN0007',
                'description'   => 'Alfuzosin HCL',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Alitretinoin',
                'code'          => 'MGN0008',
                'description'   => 'Alitretinoin',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Allopurinol Tablet',
                'code'          => 'MGN0009',
                'description'   => 'Allopurinol Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Alprazolam',
                'code'          => 'MGN0010',
                'description'   => 'Alprazolam',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Altretamine',
                'code'          => 'MGN0011',
                'description'   => 'Altretamine',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amiodarone Tablet',
                'code'          => 'MGN0012',
                'description'   => 'Amiodarone Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amitriptyline Tablet',
                'code'          => 'MGN0013',
                'description'   => 'Amitriptyline Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amlodipine And Valsartan',
                'code'          => 'MGN0014',
                'description'   => 'Amlodipine And Valsartan',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amlodipine Besylate',
                'code'          => 'MGN0015',
                'description'   => 'Amlodipine Besylate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amlodipine, Valsartan, Hydrochlorothiazide',
                'code'          => 'MGN0016',
                'description'   => 'Amlodipine, Valsartan, Hydrochlorothiazide',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amlodipine/Benazepril Capsule',
                'code'          => 'MGN0017',
                'description'   => 'Amlodipine/Benazepril Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Amoxapine Tablet',
                'code'          => 'MGN0018',
                'description'   => 'Amoxapine Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Anastrazole',
                'code'          => 'MGN0019',
                'description'   => 'Anastrazole',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Antihypertensive Combinations',
                'code'          => 'MGN0020',
                'description'   => 'Antihypertensive Combinations',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Artificial Tears 1.4% Drops (OTC)',
                'code'          => 'MGN0021',
                'description'   => 'Artificial Tears 1.4% Drops (OTC)',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Aspirin EC Tablet (OTC)',
                'code'          => 'MGN0021',
                'description'   => 'Aspirin EC Tablet (OTC)',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Atenolol Tablet',
                'code'          => 'MGN0022',
                'description'   => 'Atenolol Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Atenolol/Chlorthalidone Tablet',
                'code'          => 'MGN0023',
                'description'   => 'Atenolol/Chlorthalidone Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Atorvastatin Calcium',
                'code'          => 'MGN0024',
                'description'   => 'Atorvastatin Calcium',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Augmented Betamethasone Dipropionate',
                'code'          => 'MGN0025',
                'description'   => 'Augmented Betamethasone Dipropionate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Azathioprine',
                'code'          => 'MGN0026',
                'description'   => 'Azathioprine',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Azelastine Nasal Spray',
                'code'          => 'MGN0027',
                'description'   => 'Azelastine Nasal Spray',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Baclofen Tablet',
                'code'          => 'MGN0028',
                'description'   => 'Baclofen Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Benazepril HCTZ Tablet',
                'code'          => 'MGN0029',
                'description'   => 'Benazepril HCTZ Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Benazepril Tablet',
                'code'          => 'MGN0030',
                'description'   => 'Benazepril Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Benzonatate',
                'code'          => 'MGN0031',
                'description'   => 'Benzontate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Benzonatate Capsule',
                'code'          => 'MGN0032',
                'description'   => 'Benzonatate Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Benztropine Tablet',
                'code'          => 'MGN0033',
                'description'   => 'Benztropine Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Bethanechol Tablet',
                'code'          => 'MGN0034',
                'description'   => 'Bethanechol Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Bicalutamide',
                'code'          => 'MGN0035',
                'description'   => 'Bicalutamide',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Bisoprolol/HCTZ Tablet',
                'code'          => 'MGN0036',
                'description'   => 'Bisoprolol/HCTZ Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Brimonidine Tartrate',
                'code'          => 'MGN0037',
                'description'   => 'Brimonidine Tartrate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Bromocriptine Tablet',
                'code'          => 'MGN0038',
                'description'   => 'Bromocriptine Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Budesonide Inhalation Suspension',
                'code'          => 'MGN0039',
                'description'   => 'Budesonide Inhalation Suspension',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Bupropion HCL',
                'code'          => 'MGN0040',
                'description'   => 'Bupropion HCL',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Bupropion HCL Tablet',
                'code'          => 'MGN0041',
                'description'   => 'Bupropion HCL Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Buspirone Tablet',
                'code'          => 'MGN0042',
                'description'   => 'Buspirone Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Calcitonin-Salmon (rDNA Origin)',
                'code'          => 'MGN0043',
                'description'   => 'Calcitonin-Salmon (rDNA Origin)',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Calcitriol Capsule',
                'code'          => 'MGN0044',
                'description'   => 'Calcitriol Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Calcium Acetate',
                'code'          => 'MGN0045',
                'description'   => 'Calcium Acetate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Candesartan Cilexetil-Hydrochlorothiazide',
                'code'          => 'MGN0046',
                'description'   => 'Candesartan Cilexetil-Hydrochlorothiazide',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Candesartan Cilextil',
                'code'          => 'MGN0047',
                'description'   => 'Candesartan Cilextil',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Capsaicin Cream, 0.035% (OTC)',
                'code'          => 'MGN0048',
                'description'   => 'Capsaicin Cream, 0.035% (OTC)',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Captopril Tablet',
                'code'          => 'MGN0049',
                'description'   => 'Captopril Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Carbamazepine Tablet',
                'code'          => 'MGN0050',
                'description'   => 'Carbamazepine Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Carbidopa/Levo SR Tablet',
                'code'          => 'MGN0051',
                'description'   => 'Carbidopa/Levo SR Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Carbidopa/Levo Tablet',
                'code'          => 'MGN0052',
                'description'   => 'Carbidopa/Levo Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Carvedilol',
                'code'          => 'MGN0053',
                'description'   => 'Carvedilol',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Cetirizine HCL Tablet - OTC',
                'code'          => 'MGN0054',
                'description'   => 'Cetirizine HCL Tablet - OTC',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Cevimeline HCL',
                'code'          => 'MGN0055',
                'description'   => 'Cevimeline HCL',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Chlordiazepoxide Capsule',
                'code'          => 'MGN0056',
                'description'   => 'Chlordiazepoxide Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Chlorpromazine HCL',
                'code'          => 'MGN0057',
                'description'   => 'Chlorpromazine HCL',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Chlorthalidone Tablet',
                'code'          => 'MGN0058',
                'description'   => 'Chlorthalidone Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Cholestyramine',
                'code'          => 'MGN0059',
                'description'   => 'Cholestyramine',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Cilostazol Tablet',
                'code'          => 'MGN0060',
                'description'   => 'Cilostazol Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Citalopram Tablet',
                'code'          => 'MGN0061',
                'description'   => 'Citalopram Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Clindamycin Phosphate',
                'code'          => 'MGN0062',
                'description'   => 'Clindamycin Phosphate',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Clonazepam Tablet',
                'code'          => 'MGN0063',
                'description'   => 'Clonazepam Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Clonidine HCL Tablets',
                'code'          => 'MGN0064',
                'description'   => 'Clonidine HCL Tablets',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Clonidine Patch',
                'code'          => 'MGN0065',
                'description'   => 'Clonidine Patch',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Clopidogrel Bisulfate Tablets',
                'code'          => 'MGN0066',
                'description'   => 'Clopidogrel Bisulfate Tablets',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Clotrimazole/Betamethasone Cream',
                'code'          => 'MGN0067',
                'description'   => 'Clotrimazole/Betamethasone Cream',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Colestipol HCL',
                'code'          => 'MGN0068',
                'description'   => 'Colestipol HCL',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Decitabine',
                'code'          => 'MGN0069',
                'description'   => 'Decitabine',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Dexmethylphenidate HCL Tablet',
                'code'          => 'MGN0070',
                'description'   => 'Dexmethylphenidate HCL Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Dextroamphetamine Sulfate ER Capsule',
                'code'          => 'MGN0071',
                'description'   => 'Dextroamphetamine Sulfate ER Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Dextroamphetamine-Amphetamine ER Capsule',
                'code'          => 'MGN0072',
                'description'   => 'Dextroamphetamine-Amphetamine ER Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Dextroamphetamine-Amphetamine Tablet',
                'code'          => 'MGN0073',
                'description'   => 'Dextroamphetamine-Amphetamine Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Diazepam Tablet',
                'code'          => 'MGN0074',
                'description'   => 'Diazepam Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Diclofenac Ec Tablet',
                'code'          => 'MGN0075',
                'description'   => 'Diclofenac Ec Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Diclofenac ER Tablet',
                'code'          => 'MGN0076',
                'description'   => 'Diclofenac ER Tablet',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
            [
                'name'          => 'Dicyclomine Capsule',
                'code'          => 'MGN0077',
                'description'   => 'Dicyclomine Capsule',
                'status'        => true,
                'created_at'    => Carbon::now(),
                'updated_at'    => Carbon::now(),
            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
//            [
//                'name'          => 'Name',
//                'code'          => 'MGN0001',
//                'description'   => 'Description',
//                'status'        => true,
//                'created_at'    => Carbon::now(),
//                'updated_at'    => Carbon::now(),
//            ],
        ];

        DB::table(config('access.medicine_generic_name_table'))->insert($medicineGenericNames);

        $this->enableForeignKeys();
    }
}
