<?php

use Illuminate\Database\Seeder;
use Database\DisableForeignKeys;
use Database\TruncateTable;
use Carbon\Carbon;

class PharmaceuticalsTableSeeder extends Seeder
{
    use DisableForeignKeys, TruncateTable;

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->disableForeignKeys();

        $this->truncate(config('access.pharmaceuticals_table'));

        $pharmaceuticalCompanies = [
            [
                'name'                  => 'Square Pharmaceuticals Ltd',
                'phone'                 => '01234567890',
                'email'                 => 'email0@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Beximco Pharmaceuticals Ltd',
                'phone'                 => '01234567891',
                'email'                 => 'email1@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Incepta Pharmaceutical Ltd',
                'phone'                 => '01234567892',
                'email'                 => 'email2@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Renata Limited',
                'phone'                 => '01234567893',
                'email'                 => 'email3@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'ACI Limited',
                'phone'                 => '01234567894',
                'email'                 => 'email4@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'ACME Laboratories Ltd',
                'phone'                 => '01234567895',
                'email'                 => 'email5@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Aristopharma Ltd',
                'phone'                 => '01234567896',
                'email'                 => 'email6@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'General Pharmaceutical Ltd',
                'phone'                 => '01234567897',
                'email'                 => 'email7@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Globe Pharmaceuticals Ltd',
                'phone'                 => '01234567898',
                'email'                 => 'email8@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Healthcare Pharmaceuticals Limited',
                'phone'                 => '01234567899',
                'email'                 => 'email9@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Bio-Pharma Laboratories Ltd',
                'phone'                 => '01234567910',
                'email'                 => 'email10@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Opsonin Pharma Ltd',
                'phone'                 => '01234567911',
                'email'                 => 'email11@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Silva Pharmaceuticals Ltd',
                'phone'                 => '01234567912',
                'email'                 => 'email12@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Jayson Pharmaceuticals Ltd',
                'phone'                 => '01234567913',
                'email'                 => 'email13@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Drug International Limited',
                'phone'                 => '01234567914',
                'email'                 => 'email14@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Beacon Pharmaceuticals',
                'phone'                 => '01234567915',
                'email'                 => 'email15@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Gaco Pharmaceuticals',
                'phone'                 => '01234567916',
                'email'                 => 'email16@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Eskayef Bangladesh Ltd',
                'phone'                 => '01234567917',
                'email'                 => 'email17@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'GlaxoSmithKline Bangladesh Limited',
                'phone'                 => '01234567918',
                'email'                 => 'email18@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Nuvista Pharma Ltd',
                'phone'                 => '01234567919',
                'email'                 => 'email19@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Zuellig Pharma Bangladesh Ltd',
                'phone'                 => '01234567920',
                'email'                 => 'email20@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Novo Nordisk A/S',
                'phone'                 => '01234567921',
                'email'                 => 'email21@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Novartis (Bangladesh) Ltd',
                'phone'                 => '01234567922',
                'email'                 => 'email22@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Sandoz Pharmaceuticals Ltd',
                'phone'                 => '01234567923',
                'email'                 => 'email23@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'IBN SINA Pharmaceutical Industry Ltd',
                'phone'                 => '01234567924',
                'email'                 => 'email24@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Popular Pharmaceuticals Ltd',
                'phone'                 => '01234567925',
                'email'                 => 'email25@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Kemiko Pharmaceuticals Ltd',
                'phone'                 => '01234567926',
                'email'                 => 'email26@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'NAVANA Pharmaceuticals Ltd',
                'phone'                 => '01234567927',
                'email'                 => 'email27@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'SOMATEC Pharmaceuticals Ltd',
                'phone'                 => '01234567928',
                'email'                 => 'email28@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Rangs Pharmaceuticals Ltd',
                'phone'                 => '01234567929',
                'email'                 => 'email29@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'Sharif Pharmaceuticals Ltd',
                'phone'                 => '01234567930',
                'email'                 => 'email30@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
            [
                'name'                  => 'MonicoPharma Limited',
                'phone'                 => '01234567931',
                'email'                 => 'email31@email.com',
                'company_type'          => 'local',
                'registration_status'   => 'applied',
                'status'                => true,
                'created_at'            => Carbon::now(),
                'updated_at'            => Carbon::now(),
            ],
        ];

        DB::table(config('access.pharmaceuticals_table'))->insert($pharmaceuticalCompanies);

        $this->enableForeignKeys();
    }
}
